#!/bin/bash
set -e
VP="$(cat package.json | grep '"version"' | head -1 | cut -d\" -f4)"
VPL="$(cat package-lock.json | grep '"version"' | head -1 | cut -d\" -f4)"
VPP="$(cat plugin.xml | grep -E '^[ ]+version="' | head -1 | cut -d \" -f2)"

if [ "x$VP" = "x$VPL" ] && [ "x$VP" = "x$VPP" ]; then
  echo "All version numbers match: $VP"
else
  echo "Version numbers mismatch:"
  echo "    package-lock.json: $VP"
  echo "    package.json: $VPL"
  echo "    plugin.xml: $VPP"
  exit 1
fi
