#!/bin/bash
set -e
VP="$(cat package.json | grep '"version"' | head -1 | cut -d\" -f4)"
VPL="$(cat package-lock.json | grep '"version"' | head -1 | cut -d\" -f4)"
VPP="$(cat plugin.xml | grep -E '^[ ]+version="' | head -1 | cut -d \" -f2)"
VJ="$(cat src/ts/store.ts | grep -E "PLUGIN_VERSION = '" | head -1 | cut -d \' -f2)"

if [ "x$1" = "x--edit" ]; then
  exec vim package.json package-lock.json plugin.xml src/ts/store.ts RELEASE_NOTES.md
fi

echo
echo "    package.json:      $VP"
echo "    package-lock.json: $VPL"
echo "    plugin.xml:        $VPP"
echo "    src/ts/store.ts:   $VJ"
echo

if [ "x$VP" = "x$VPL" ] && [ "x$VP" = "x$VPP" ] && [ "x$VP" = "x$VJ" ]; then
  echo "All version numbers match: $VP"
else
  echo "VERSION NUMBERS MISMATCH"
  exit 1
fi
