//!
//! ## Generating the documentation
//!
//! The documentation is generated by running `make doc`. This command will update doc/api.md and doc/contributor-guide.md
//!
//! The content of those files is retrieve from the typescript source code.
//!
//! Lines starting with "//!" will be included in the contributor documentation.
//! Lines starting with "//:" will be included in the user documentation.
//!

/** cordova-plugin-purchase global namespace */
namespace CDVPurchase2 {}
